<?php

/**
 * @file
 * Contains demo_frontend_api.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function demo_frontend_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the demo_frontend_api module.
    case 'help.page.demo_frontend_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Homework for lesson 4') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function demo_frontend_api_theme() {
  return array(
    'demo_frontend_api_theme' => array(
      'template' => 'demo_frontend_api_theme_template',
      'variables' => ['title' => NULL, 'body' => NULL],
    ),
  );
}
