demo_currencies.currency.*:
  type: config_entity
  label: 'Currency config'
  mapping:
    code:
      type: string
      label: 'Code'
    name:
      type: label
      label: 'Name'
    display_on_page:
      type: boolean
      label: 'Display on currencies page'
    display_in_block:
      type: boolean
      label: 'Display in block'
